# This is the version of the docker file format - not docker itself
version: "3.9"

services:
  # Each service is a docker container
  app: 
    # What is the docker container building
    build: ./flask-app
    # [mounts/imports] directories from your computer into the specified container directories 
    volumes: 
      - ./flaskApp:/app
    # external : internal port 
    # external = other machines on a network
    # internal = other containers within the same docker network 
    ports:
      - "5001:5000"


  # db:
  #   network_mode: bridge
  #   image: postgres:13.0-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=password
    
  #   #This maps the internal docker port to an external port on your computer 
  #   ports:
  #     - 5432:5432
  #   # We can mount a volume in our computer meaning that isntead of having to build 
  #   # a new image every time we have made changes to the code base
  #   volumes:
  #     - ./data:/var/lib/postgresql/data

  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  # redis:
  #   image: "redis:alpine"
